name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y make docker-compose

      - name: Build project
        run: make build

      - name: Build and start Docker containers
        run: make run

      - name: Run PHP CodeSniffer
        run: make code-quality

      - name: Stop and remove Docker containers
        run: make stop